### ISSUE TITLE
How can I simulate some interchromosomal translocations？

### ISSUE THREAD

**Issue by dcy99** [genomech/Charm#4]
Hi,
Can Charm to simulate some interchromosomal translocations?
For example, a section of two chromosomes is exchanged,also called balanced translocation.

**Comment by NuriddinovMA** [comment]
Apologies for the delayed response.
Yes, Сarm can simulate the interchromosomal translocations. For example, loci chr1:0-5,000,000 and chr2:0-4,000,000 are exchanged between chr1 and chr2. [The best way to describe](https://github.com/genomech/Charm?tab=readme-ov-file#the-svs-description) this balanced translocation is:
'''
test	balanced	chr1	0	5000000	!>	der1 1
test	balanced	chr2	4000000	+	>>	der1	1
test	balanced	chr2	0	4000000	>>	der2	1
test	balanced	chr1	5000000	+	>!	der2	1
'''
where chr1:5,000,000 and chr2:4,000,000 are the genome coordinates of breakpoints.
