### ISSUE TITLE
How to simulate multiple structural variations on a sample？

### ISSUE THREAD

**Issue by TomWang666** [genomech/Charm#7]
Thank you for providing such a good tool. I tried to simulate various types and lengths of structural variations on a normal cell line, and a total of 40 were simulated at once. However, I have been running for 15 days and still have no results. I am wondering if there is a problem with the way I used the tool to simulate? So, may I ask if I should continue to wait or simulate in batches?

**Comment by NuriddinovMA** [comment]
Sorry for the late reply.
In the present version, multi-threading has not yet been implemented and there are two critical points that could cause a substantial increase in the processing time:
1) generation of all pairs of chromosomes for the wild type;
2) generation of many pairs of chromosomes, when there are many rearrangements scattered across different chromosomes.
The solution to the problem in both cases would be to define a specific pair of chromosomes to be modeled using the parameters “chosen_chroms_from = ” and “chosen_chroms_to = ” in the simulation (or wild type) section and run the simulation for each such pair of chromosomes separately, as independent tasks.
After the “sim” and “lift” steps have passed, the output files just need to be put into one folder and the program launched from the “hic” stage.
